config/routes.rb
Homework2::Application.routes.draw do
  
  resources :vaccinations

  resources :vaccines

  resources :visits

  resources :pets

  resources :animals

  root :to => 'Home#index'
  
  resources :owners #vaccination, animals, ..
  
  
  match 'Home/about' => 'Home#about'
  match 'Home/index' => 'Home#index'
  match 'Home/contact' => 'Home#contact'
  match 'Home/privacy' => 'Home#privacy'
  
  
  get "owners/index"

  get "owners/show"

  get "owners/new"

  get "owners/edit"

  get "owners/create"

  get "owners/update"

  get "owners/destroy"

  get "home/about"

  get "home/contact"

  get "home/index"

  get "home/privacy"

end

app/models/vaccination.rb
class Vaccination < ActiveRecord::Base
  attr_accessible :id, :vaccine_id, :visit_id
  	belongs_to :visit
	belongs_to :vaccine
	
  
  scope :latest, lambda{|num| limit(num).order('visit_date DESC')}  ##to make sure we will get the latest numbers.

  scope :chronological, joins(:visit) #edit
  scope :for_vaccine, lambda{|vaccine_id| where('vaccine_id = ?', vaccine_id)}
 
  scope :for_visit, lambda{|visit_id| where('visit_id = ?', visit_id)}
 
 private


def vaccine_offered_by_QATS
		vaccOffer == false
	if self.vaccine_id.exists? 
		vaccOffer == true
	end
	if vaccOffer == false
	print "Error, the vaccination is not offered by QATS."
	end
end

def vaccine_matches_animal_type
	vaccMatch == false
	if @vaccine.id == self.vaccine_id 
		vaccMatch == true
	end
	if vaccMatch == false
	print "Error, the vaccination does not match the animal type."
	end
end

end

app/controllers/vaccinations_controller.rb
class VaccinationsController < ApplicationController
  # GET /vaccinations
  # GET /vaccinations.json
  def index
    @vaccinations = Vaccination.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vaccinations }
    end
  end

  # GET /vaccinations/1
  # GET /vaccinations/1.json
  def show
    @vaccination = Vaccination.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vaccination }
    end
  end

  # GET /vaccinations/new
  # GET /vaccinations/new.json
  def new
    @vaccination = Vaccination.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vaccination }
    end
  end

  # GET /vaccinations/1/edit
  def edit
    @vaccination = Vaccination.find(params[:id])
  end

  # POST /vaccinations
  # POST /vaccinations.json
  def create
    @vaccination = Vaccination.new(params[:vaccination])

    respond_to do |format|
      if @vaccination.save
        format.html { redirect_to @vaccination, notice: 'Created new vaccination #{@vaccination.id}.' }
        format.json { render json: @vaccination, status: :created, location: @vaccination }
      else
        format.html { render action: "new" }
        format.json { render json: @vaccination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vaccinations/1
  # PUT /vaccinations/1.json
  def update
    @vaccination = Vaccination.find(params[:id])

    respond_to do |format|
      if @vaccination.update_attributes(params[:vaccination])
        format.html { redirect_to @vaccination, notice: 'Vaccination was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vaccination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccinations/1
  # DELETE /vaccinations/1.json
  def destroy
    @vaccination = Vaccination.find(params[:id])
    @vaccination.destroy

    respond_to do |format|
      format.html { redirect_to vaccinations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vaccinations_helper.rb
module VaccinationsHelper
end

app/views/vaccinations/_form.html.erb
<%= form_for(@vaccination) do |f| %>
  <% if @vaccination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vaccination.errors.count, "error") %> prohibited this vaccination from being saved:</h2>

      <ul>
      <% @vaccination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :vaccine_id %><br />
    <%= f.number_field :vaccine_id %>
  </div>
  <div class="field">
    <%= f.label :visit_id %><br />
    <%= f.number_field :visit_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vaccinations/edit.html.erb
<h1>Editing vaccination</h1>

<%= render 'form' %>

<%= link_to 'Show', @vaccination %> |
<%= link_to 'Back', vaccinations_path %>

app/views/vaccinations/index.html.erb
<h1>Listing vaccinations</h1>

<table id ="vaccinations">
  <tr>
    <th>Id</th>
    <th>Vaccine</th>
    <th>Visit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vaccinations.each do |vaccination| %>
  <tr>
    <td><%= vaccination.id %></td>
    <td><%= vaccination.vaccine_id %></td>
    <td><%= vaccination.visit_id %></td>
    <td><%= link_to 'Show', vaccination %></td>
    <td><%= link_to 'Edit', edit_vaccination_path(vaccination) %></td>
    <td><%= link_to 'Destroy', vaccination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vaccination', new_vaccination_path %>

app/views/vaccinations/new.html.erb
<h1>New vaccination</h1>

<%= render 'form' %>

<%= link_to 'Back', vaccinations_path %>

app/views/vaccinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @vaccination.id %>
</p>

<p>
  <b>Vaccine:</b>
  <%= @vaccination.vaccine_id %>
</p>

<p>
  <b>Visit:</b>
  <%= @vaccination.visit_id %>
</p>


<%= link_to 'Edit', edit_vaccination_path(@vaccination) %> |
<%= link_to 'Back', vaccinations_path %>