config/routes.rb
Homework2::Application.routes.draw do
  
  resources :vaccinations

  resources :vaccines

  resources :visits

  resources :pets

  resources :animals

  root :to => 'Home#index'
  
  resources :owners #vaccination, animals, ..
  
  
  match 'Home/about' => 'Home#about'
  match 'Home/index' => 'Home#index'
  match 'Home/contact' => 'Home#contact'
  match 'Home/privacy' => 'Home#privacy'
  
  
  get "owners/index"

  get "owners/show"

  get "owners/new"

  get "owners/edit"

  get "owners/create"

  get "owners/update"

  get "owners/destroy"

  get "home/about"

  get "home/contact"

  get "home/index"

  get "home/privacy"

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :id, :notes, :pet_id, :visit_date, :weight
  
  belongs_to :pet
  has_many :vaccinations
  has_many :vaccines, :through => :vaccinations
  
  
  validates :pet_id, :weight, :visit_date, :presence =>true
  validates :weight, :numericality => {:only_integer => true, :greater_than => 0, :allow_blank => true, :allow_nil => true}
  
  scope :chronological, order('visit_date DESC')
  scope :for_pet, lambda{|pet_id| where('pet_id = ?', pet_id)}
  scope :latest, lambda{|num| limit(num).order('visit_date DESC')}  ##to make sure we will get the latest numbers.

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @visit = Visit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Created new visit #{@visit.id}.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :pet_id %><br />
    <%= f.number_field :pet_id %>
  </div>
  <div class="field">
    <%= f.label :visit_date %><br />
    <%= f.date_select :visit_date %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<table id="visits">
  <tr>
    <th>Id</th>
    <th>Pet</th>
    <th>Visit date</th>
    <th>Weight</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visits.each do |visit| %>
  <tr>
    <td><%= visit.id %></td>
    <td><%= visit.pet_id %></td>
    <td><%= visit.visit_date %></td>
    <td><%= visit.weight %></td>
    <td><%= visit.notes %></td>
    <td><%= link_to 'Show', visit %></td>
    <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
    <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @visit.id %>
</p>

<p>
  <b>Pet:</b>
  <%= @visit.pet_id %>
</p>

<p>
  <b>Visit date:</b>
  <%= @visit.visit_date %>
</p>

<p>
  <b>Weight:</b>
  <%= @visit.weight %>
</p>

<p>
  <b>Notes:</b>
  <%= @visit.notes %>
</p>


<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>