config/routes.rb
Homework2::Application.routes.draw do
  
  resources :vaccinations

  resources :vaccines

  resources :visits

  resources :pets

  resources :animals

  root :to => 'Home#index'
  
  resources :owners #vaccination, animals, ..
  
  
  match 'Home/about' => 'Home#about'
  match 'Home/index' => 'Home#index'
  match 'Home/contact' => 'Home#contact'
  match 'Home/privacy' => 'Home#privacy'
  
  
  get "owners/index"

  get "owners/show"

  get "owners/new"

  get "owners/edit"

  get "owners/create"

  get "owners/update"

  get "owners/destroy"

  get "home/about"

  get "home/contact"

  get "home/index"

  get "home/privacy"

end

app/models/vaccine.rb
class Vaccine < ActiveRecord::Base
  attr_accessible :animal_id, :duration, :id, :name
  
  belongs_to :animal
  has_many :vaccinations
  has_many :visits, :through => :vaccinations
  
before_save :check_vaccine_duration

validates :name, :animal_id, :presence => true
validates :duration, :numericality => {:only_integer => true, :greater_than => 0, :allow_blank => true, :allow_nil => true}

scope :alphabetical, order('name')
scope :for_animal, lambda{|animal_id| where('animal_id = ?', animal_id)}

private

def check_vaccine_duration
	dur = self.duration
	self.duration = 7300 if dur.nil? || dur.blank?
end
end

app/controllers/vaccines_controller.rb
class VaccinesController < ApplicationController
  # GET /vaccines
  # GET /vaccines.json
  def index
    @vaccines = Vaccine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vaccines }
    end
  end

  # GET /vaccines/1
  # GET /vaccines/1.json
  def show
    @vaccine = Vaccine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vaccine }
    end
  end

  # GET /vaccines/new
  # GET /vaccines/new.json
  def new
    @vaccine = Vaccine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vaccine }
    end
  end

  # GET /vaccines/1/edit
  def edit
    @vaccine = Vaccine.find(params[:id])
  end

  # POST /vaccines
  # POST /vaccines.json
  def create
    @vaccine = Vaccine.new(params[:vaccine])

    respond_to do |format|
      if @vaccine.save
        format.html { redirect_to @vaccine, notice: 'Created new vaccine #{@vaccine.name}.' }
        format.json { render json: @vaccine, status: :created, location: @vaccine }
      else
        format.html { render action: "new" }
        format.json { render json: @vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vaccines/1
  # PUT /vaccines/1.json
  def update
    @vaccine = Vaccine.find(params[:id])

    respond_to do |format|
      if @vaccine.update_attributes(params[:vaccine])
        format.html { redirect_to @vaccine, notice: 'Vaccine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccines/1
  # DELETE /vaccines/1.json
  def destroy
    @vaccine = Vaccine.find(params[:id])
    @vaccine.destroy

    respond_to do |format|
      format.html { redirect_to vaccines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vaccines_helper.rb
module VaccinesHelper
end

app/views/vaccines/_form.html.erb
<%= form_for(@vaccine) do |f| %>
  <% if @vaccine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vaccine.errors.count, "error") %> prohibited this vaccine from being saved:</h2>

      <ul>
      <% @vaccine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :animal_id %><br />
    <%= f.number_field :animal_id %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vaccines/edit.html.erb
<h1>Editing vaccine</h1>

<%= render 'form' %>

<%= link_to 'Show', @vaccine %> |
<%= link_to 'Back', vaccines_path %>

app/views/vaccines/index.html.erb
<h1>Listing vaccines</h1>

<table id="vaccines">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Animal</th>
    <th>Duration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vaccines.each do |vaccine| %>
  <tr>
    <td><%= vaccine.id %></td>
    <td><%= vaccine.name %></td>
    <td><%= vaccine.animal_id %></td>
    <td><%= vaccine.duration %></td>
    <td><%= link_to 'Show', vaccine %></td>
    <td><%= link_to 'Edit', edit_vaccine_path(vaccine) %></td>
    <td><%= link_to 'Destroy', vaccine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vaccine', new_vaccine_path %>

app/views/vaccines/new.html.erb
<h1>New vaccine</h1>

<%= render 'form' %>

<%= link_to 'Back', vaccines_path %>

app/views/vaccines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @vaccine.id %>
</p>

<p>
  <b>Name:</b>
  <%= @vaccine.name %>
</p>

<p>
  <b>Animal:</b>
  <%= @vaccine.animal_id %>
</p>

<p>
  <b>Duration:</b>
  <%= @vaccine.duration %>
</p>


<%= link_to 'Edit', edit_vaccine_path(@vaccine) %> |
<%= link_to 'Back', vaccines_path %>